---
title: "Berozovon kenttätyömatka"
output: html_document
editor_options: 
  chunk_output_type: console
---

Tutkijatohtori Susanna Virtanen ja maisteri Niko Partanen valmistelevat Helsingin yliopistossa kenttätyömatkaa Berjozovon taajamaan Siperiassa. Matkan ajankohta on kesä 2020, ja tutkimusryhmä koostuu noin kymmenestä mansin ja komin kielten asiantuntijasta.

Matkaa järjestäviä tahoja ovat Helsingin yliopisto ja Suomalais-Ugrilainen Seura. Matkan tavoitteena on tuottaa tuoreita dokumentoivia aineistoja mansin ja komin kielistä, keskittyen mm. historialliseen monikielisyyteen alueella.

Tutkimuksessa otetaan mahdollisimman laajalti huomioon jo olemassa olevat materiaalit. Esimerkiksi Artturi Kanniston kenttätyömatkoilta 1900-luvun alusta on saatavilla runsas sanasto- ja valokuva-aineisto mansin kielestä. Tämän lisäksi eri mansia ja komia käsitelleet tutkimusprojektit ovat tuottaneet hankkeelle käyttökelpoisia ja arvokkaita materiaaleja.

<center>

![Matkalla Obille kalastamaan. Kannisto Artturi, kuvaaja. 1905–1906.</br>Suomalais-ugrilainen kuvakokoelma /
Antellin kokoelmat. Museovirasto - Musketti. CC-BY 4.0.](https://api.finna.fi/Cover/Show?id=musketti.M012%3ASUK35%3A67&index=0&size=large)

</center>

